# 自己 - 获取会议信息
query confByMeByToken($token: String!) {
    confByMeByToken(token: $token){
        conferenceId
        confTitle
        confName
        createTime
        updateTime
    }
}

#自己 - 参会人数统计[参会人统计列表]
query confStatisticsByMe($token: String!) {
  confStatisticsByMe(token: $token) {
    totalNum
    confStatistics {
      actualNum
      lateNum
      nonArrNum
      dateTime
    }
  }
}

fragment person on Person {
  personId
  idCard
  name
  gender
  photoUrl
  imageUrl
  nation
  birthDay
  issueDay
  expireDay
  mobileNo
  postalAddr
  postalAddrCode
  organisation
  equipmentId
  personType
  company
  createTime
  updateTime
}

# 自己 - 未到迟到人数统计
query nonArrLateStatisticsByMe($token: String!, $pageNo: Long!, $pageSize: Long!, $status: Int!, $dateTime: String!) {
    nonArrLateStatisticsByMe(token: $token, pageNo: $pageNo, pageSize: $pageSize, status: $status, dateTime: $dateTime){
        pageNo
        pageSize
        pageTotalCount
        pageTotalRows
        pageRows{
          ...person
        }
    }
}

# 查询所有到人员的信息
query actualAttendancePersonByMe($token: String!, $pageNo: Long!, $pageSize: Long!, $dateTime: String!) {
  actualAttendancePersonByMe(token: $token, pageNo: $pageNo, pageSize: $pageSize, dateTime: $dateTime) {
    pageTotalCount
    pageTotalRows
    pageRows {
      ...person
    }
  }
}
